// @ts-check
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt(
  // Generated by `sanity typegen` in the Studio and formatted with its own
  // prettier settings, which disagree with the Nuxt stylistic rules. Nothing is
  // hand-edited here, so there is nothing to lint.
  {
    ignores: ['app/sanity/types.ts']
  }
)
