/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Callout = {
  _type: "callout";
  tone?: "tip" | "caution" | "safety";
  text?: string;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote?: string;
  person?: string;
  result?: string;
};

export type PersonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "person";
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  steps?: Array<{
    title?: string;
    body?: Array<
      | {
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?:
            "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }
      | ({
          _key: string;
        } & Callout)
    >;
    _type: "step";
    _key: string;
  }>;
  coach?: PersonReference;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type BodyRegionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "bodyRegion";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Muscle = {
  _id: string;
  _type: "muscle";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  bodyRegion?: BodyRegionReference;
  diagram?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type BodyRegion = {
  _id: string;
  _type: "bodyRegion";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  description?: string;
};

export type MuscleReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "muscle";
};

export type EquipmentReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "equipment";
};

export type Exercise = {
  _id: string;
  _type: "exercise";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  instructions?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & Callout)
  >;
  demoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  demoVideoUrl?: string;
  muscles?: Array<
    {
      _key: string;
    } & MuscleReference
  >;
  equipment?: EquipmentReference;
  difficulty?: "beginner" | "intermediate" | "advanced";
};

export type EquipmentCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "equipmentCategory";
};

export type Equipment = {
  _id: string;
  _type: "equipment";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  category?: EquipmentCategoryReference;
};

export type EquipmentCategory = {
  _id: string;
  _type: "equipmentCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  description?: string;
};

export type ExerciseReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "exercise";
};

export type Workout = {
  _id: string;
  _type: "workout";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  order?: number;
  exercises?: Array<
    {
      _key: string;
    } & ExerciseReference
  >;
  estimatedDuration?: number;
  coach?: PersonReference;
};

export type WorkoutReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "workout";
};

export type Program = {
  _id: string;
  _type: "program";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  goal?: string;
  focus?:
    | "strength"
    | "hypertrophy"
    | "fat-loss"
    | "endurance"
    | "mobility"
    | "foundations";
  duration?: number;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  workouts?: Array<
    {
      _key: string;
    } & WorkoutReference
  >;
  coach?: PersonReference;
  firstPublished?: string;
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  bio?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Callout
  | Testimonial
  | PersonReference
  | Article
  | Slug
  | BodyRegionReference
  | SanityImageAssetReference
  | Muscle
  | SanityImageCrop
  | SanityImageHotspot
  | BodyRegion
  | MuscleReference
  | EquipmentReference
  | Exercise
  | EquipmentCategoryReference
  | Equipment
  | EquipmentCategory
  | ExerciseReference
  | Workout
  | WorkoutReference
  | Program
  | Person
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/app/sanity/queries.ts
// Variable: PROGRAMS_QUERY
// Query: *[_type == "program" && defined(slug.current)] | order(title asc){  _id, title, slug, focus, duration}
export type PROGRAMS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  focus:
    | "endurance"
    | "fat-loss"
    | "foundations"
    | "hypertrophy"
    | "mobility"
    | "strength"
    | null;
  duration: number | null;
}>;

// Source: ../web/app/sanity/queries.ts
// Variable: PROGRAM_QUERY
// Query: *[_type == "program" && slug.current == $slug][0]{  _id, title, description, focus, duration,  coach->{ name, slug },  workouts[]->{ _id, title, slug, order, estimatedDuration }}
export type PROGRAM_QUERY_RESULT = {
  _id: string;
  title: string | null;
  description: string | null;
  focus:
    | "endurance"
    | "fat-loss"
    | "foundations"
    | "hypertrophy"
    | "mobility"
    | "strength"
    | null;
  duration: number | null;
  coach: {
    name: string | null;
    slug: Slug | null;
  } | null;
  workouts: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
    order: number | null;
    estimatedDuration: number | null;
  }> | null;
} | null;

// Source: ../web/app/sanity/queries.ts
// Variable: WORKOUT_QUERY
// Query: *[_type == "workout" && slug.current == $slug][0]{  _id, title, order, estimatedDuration,  coach->{ name },  exercises[]->{ _id, name, slug, difficulty }}
export type WORKOUT_QUERY_RESULT = {
  _id: string;
  title: string | null;
  order: number | null;
  estimatedDuration: number | null;
  coach: {
    name: string | null;
  } | null;
  exercises: Array<{
    _id: string;
    name: string | null;
    slug: Slug | null;
    difficulty: "advanced" | "beginner" | "intermediate" | null;
  }> | null;
} | null;

// Source: ../web/app/sanity/queries.ts
// Variable: EXERCISE_QUERY
// Query: *[_type == "exercise" && slug.current == $slug][0]{  _id, name, difficulty, instructions, demoVideoUrl,  muscles[]->{ name },  equipment->{ name }}
export type EXERCISE_QUERY_RESULT = {
  _id: string;
  name: string | null;
  difficulty: "advanced" | "beginner" | "intermediate" | null;
  instructions: Array<
    | ({
        _key: string;
      } & Callout)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
  > | null;
  demoVideoUrl: string | null;
  muscles: Array<{
    name: string | null;
  }> | null;
  equipment: {
    name: string | null;
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "program" && defined(slug.current)] | order(title asc){\n  _id, title, slug, focus, duration\n}': PROGRAMS_QUERY_RESULT;
    '*[_type == "program" && slug.current == $slug][0]{\n  _id, title, description, focus, duration,\n  coach->{ name, slug },\n  workouts[]->{ _id, title, slug, order, estimatedDuration }\n}': PROGRAM_QUERY_RESULT;
    '*[_type == "workout" && slug.current == $slug][0]{\n  _id, title, order, estimatedDuration,\n  coach->{ name },\n  exercises[]->{ _id, name, slug, difficulty }\n}': WORKOUT_QUERY_RESULT;
    '*[_type == "exercise" && slug.current == $slug][0]{\n  _id, name, difficulty, instructions, demoVideoUrl,\n  muscles[]->{ name },\n  equipment->{ name }\n}': EXERCISE_QUERY_RESULT;
  }
}
